{% set name = "jsmin" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jsmin-{{ version }}.tar.gz
  sha256: 88fc1bd6033a47c5911dbcada7d279c7a8b7ad0841909590f6a742c20c4d2e08

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - jsmin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tikitu/jsmin/
  summary: JavaScript minifier.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
    - daf
