# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "hbgbBFdj0HjpRrFde27Bj8qapyCT/C/v0+346tptFegIQGWglgMjOMgIymwOCIAwxp9HnLBAaG9u84nkIBYGE3v+dNrX2e1kWjBv57X4Xnh4CiWyxnuy0k4rRWHydVhxdTu4QiTb6olGeaYlix/YNI0X/kxAmEohRKP4mq2HkarAY+49PYpZhEW/5UoSeNYINzJlRXsyN8Iab8qsofoEtpzyg3TscQp3H2K/yNRkI3vwJDeyJvep/3CcP0aG8BjQlH197KnIc69nMo/ks17grQWx2WAoK/6T1QIrDpp+TduuGqghcjW2nF7c4e8iQq6KdE4jiZVuV9w9lmIVLpJsScDK0z++ABUP+A4/Hnv1mILcQAe+QmjEMyJQu+z4Xy3M214ccLovm6Z/h+fiK5HCS1ciUf2Ttpuh6HsrYHzosm5Lj7qmIadyFipn2o6zlBNXguNE8Trk4FcZVNfHdxcfvbsesgoalCCZTaq+P+pcf5nb8JBLUdAknS2RN5gBHW71SAXjQnT24zQFgjMBP8To0D7a8OdW6sR7P03rOS6DeAHKOfGfrPVw4jDHGhu8RId2e2Ji2GSsPq3mQ7YJC/jV8FXHPynsmdoBcq5fzG9TL+A0xCj8+kpg2wkULG5N3/U0EEsZo35zCBBpnnbCSV52jb6D7+99L/9+MziN2vJPOfs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
