travis:
  secure:
    BINSTAR_TOKEN: bDc1RMgr345+MFtfhOcRGBKQMh1lqVlX47iAEhf9HfZx1W6lE2I/k80ux+exmzjIIVw5TyDznTM+KiPeL21C8TW+0nE50HUfuqzJW8rTZe6VwnTTHXrHS/Z4lScMouW4REn5LL3lJNcF7R16vTlyCW/Md0Wgj/fQkBiNrXKiCRAnvErCisCKVBjHg14txGjG4tIYYocRf3lI1fbc7DZa7uQB0xXCypxQxBcnYLEXuMjWNjkQUD25Eruq3ix1sA1Bf78d5cQNbFQpnjgpHhThzZOZkNLBoUQ1usOxlHVK7jRwTSnswEnUOhkvdGQKOMZJzlLjl/jCu8IjLRVefF1sGX4ktDgL9YUi358VrQx/+3oQ6QCYpL7qE9baf5hVa00VJp55nCPVZ3fsnX4qRvOl9BNtdxUb+gv73dmPY7gj3DYCM0+ZeCKorIgTDznCwSJOZ5yRdgirxpQEn7KCjOCum23gwWKJscfvR6MDTJxmBeevZYir/Z440+Y1fn1tL4E8XRLfkZyZMi0CsloE9qFTHouDYhfykSFyOQDPdug00MDtcTSDGH45CC4R4UJttFfpEc92QobdNhI1Hw37P+m212QzWVjjV3lxaeJQIg96IxuzSqlsW4E8kayV9V0g4W24+oFElyj+Drs9wzlj3tnuIAJKBItVdUI+lta3i1d2IyI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
